#+title: Arduino handbook
#+author: undercover

* Cодержание :toc:
- [[#источники][Источники]]
- [[#базовый-синтаксис][Базовый синтаксис]]
  - [[#комментарии][Комментарии]]
  - [[#подключение-библиотек][Подключение библиотек]]
  - [[#функции][Функции]]
  - [[#типы-данных][Типы данных]]
  - [[#инициализация-переменной][Инициализация переменной]]
  - [[#действия-над-переменными][Действия над переменными]]
  - [[#константа][Константа]]
- [[#com-порт][COM порт]]
- [[#условия][Условия]]
  - [[#операторы-сравнения][Операторы сравнения]]
  - [[#условный-оператор-if][Условный оператор 'if']]
  - [[#логические-операторы][Логические операторы]]
  - [[#оператор-switch][Оператор 'switch']]
- [[#время][Время]]
- [[#порты-пины][Порты (пины)]]
- [[#циклы][Циклы]]
  - [[#while]['while']]
  - [[#for]['for']]
  - [[#break-и-continue]['break' и 'continue']]
- [[#функции-1][Функции]]

* Источники

|--------------------------+------|
| Официальный сайт Arduino | [[https://www.arduino.cc/reference/en/][клик]] |
| Заметки Ардуинщика       | [[https://alexgyver.ru/arduino/Arduino_lessons.pdf][клик]] |
|--------------------------+------|

* Базовый синтаксис
** Комментарии

#+begin_src c
// Однострочный комментарий
/*
 * Многострочный
 *   комментарий
 */
#+end_src

** Подключение библиотек

#+begin_src c
#include // Подключить библиотеку
#include <Servo.h>
#+end_src

** Функции

#+begin_src c
void setup() {
  // Код выполняется один раз при загрузке Arduino
}

void loop() {
  // Код выполняется бесконечно
}
#+end_src

** Типы данных

|---------------+--------------------------+--------------------------------------------------------------|
| Название      |                 Диапазон | Особенность                                                  |
|---------------+--------------------------+--------------------------------------------------------------|
| boolean       |                  0 или 1 | 'true' или 'false'                                           |
| char          |               -128...127 | Номер символа из ASCII                                       |
| byte          |                  0...255 |                                                              |
| int           |           -32768...32767 |                                                              |
| unsigned int  |                0...65535 |                                                              |
| word          |                0...65535 | То же самое что и unsigned int                               |
| long          |   -214783648...214783647 |                                                              |
| unsigned long |           0...4294967295 |                                                              |
| float         | число с плавающей точкой | Присваивать значение *ТОЛЬКО* с точкой                         |
| array         |                          | При инициализации использовать `тип переменной` `название`[] |
|---------------+--------------------------+--------------------------------------------------------------|

** Инициализация переменной

По умолчанию переменные имеют значение =0=, но им можно присвоить значение используя знак равно (=). Указывать тип данных нужно *ТОЛЬКО ПРИ ОБЪЯВЛЕНИИ*.

#+begin_src c
int number; // 0
int shnumber = 5; // 5

shnumber += 4;
#+end_src

Переменные бывают /глобальными/ и /локальными/. /Локальные/ переменные нельзя использовать в другой функции! /Глобальные/ же весят больше.

#+begin_src c
float value = 23.145; // Глобальная переменная

void setup() {
  byte aboba; // Локальная переменная
}

void loop() {
  long shlong = 141241329; // Локальная переменная
}
#+end_src

** Действия над переменными

|------------------------------------+-------------------------------------------------|
| Функция                            | Описание                                        |
|------------------------------------+-------------------------------------------------|
| pow(x, y)                          | Возведение 'x' в степень 'y'                    |
| sqr(x)                             | Возведение 'x' в квадрат                        |
| sqrt(x)                            | Вычисление *квадратного* корня 'x'                |
| cbrt(x)                            | Вычисление *кубического* корень 'x'               |
| abs(x)                             | Вычисление модуля 'x'                           |
| hypot(x, y)                        | Вычисление гипотенузы (корень(x*x + y*y))       |
| log(x)                             | Вычисление натурального логарифма 'x'           |
| fmax(x, y)                         | Возвращение большего из 'x' и 'y'               |
| fmax(x, y)                         | Возвращение большего из 'x' и 'y'               |
| sin(x)                             | Вычисление синуса 'x'                           |
| cos(x)                             | Вычисление косинуса 'x'                         |
| tan(x)                             | Вычисление тангенса 'x'                         |
| round(x)                           | Округление 'x'                                  |
| ceil(x)                            | Округление 'x' в большую сторону                |
| floor(x)                           | Округление 'x' в меньшую сторону                |
| constrain(val, min, max)           | Ограничение диапазона 'val' между 'min' и 'max' |
| map(val, min, max, newMin, newMax) | Перевод диапазона 'val' в новый диапазон        |
|------------------------------------+-------------------------------------------------|

Также есть полезные операторы, которые упрощают работу:

|----------+-----------------------|
| Оператор | Описание              |
|----------+-----------------------|
| x += y   | Прибавление 'y' к 'x' |
| x -= y   | Вычитание 'y' из 'x'  |
| x *= y   | Умножение 'x' на 'y'  |
| x /= y   | Деление 'x' на 'y'    |
| x++      | Увеличение 'x' на 1   |
| x--      | Уменьшение 'x' на 1   |
|----------+-----------------------|

** Константа
Значение константы *не изменяется*. Они чуть-чуть быстрее и немного меньше. Чтобы объявить переменную нужново время инициализации перед типом переменной написать =const=,ли инициализировать переменную при помощи =#define=

#+begin_src c
const byte myPin = 13; // константа
#+end_src

...или...

#+begin_src c
#define myPin 13 // без `=` и `;`
#+end_src

|----------------------+-------------+------------------|
| Встроенная константа |    Значение | Описание         |
|----------------------+-------------+------------------|
| M_E                  | 2.718281828 | Число Эйлера (e) |
| M_PI                 | 3.141592654 | Число 𝜋 (пи)     |
|----------------------+-------------+------------------|

* COM порт
COM порт используется для связи с Arduino. Для работы с портом существует библиотека с объектом =Serial=. Для начала его нужно открыть:

#+begin_src c
void setup() {
    Serial.begin(9600);
}
#+end_src

Для этого используется функция =.begin()=, где в скобках указывается скорость в [[https://ru.wikipedia.org/wiki/Бод][бодах]] (обычно =9600=).
Для того чтобы вывести информацию в порт используется функция =.print()=:

#+begin_src c
void setup() {
  Serial.begin(9600); // Порт нужно открывать только один раз, в 'void setup'
}

void loop() {
  Serial.print("Hello World!"); // Бесконечно выводить в порт "Hello world!" (без перевода строки)
}
#+end_src

|---------------+----------------------------------------------------|
| Функция       | Описание                                           |
|---------------+----------------------------------------------------|
| .print(x)     | Вывод в порт 'x'                                   |
| .println()    | Вывод в порт 'x' с переводом строки                |
| .available()  | Проверка на наличие входящих данных                |
| .read()       | Чтение в *символьном формате согласно ASCII*         |
| .read() - '0' | Чтение в *целочисленном формате по одной цифре*      |
| .parseInt()   | Чтение в *целочисленном формате целиком*             |
| .readString() | Чтение *строки*                                      |
| .parseFloat() | Чтение в *формате с плавающей точкой целиком*        |
| .setTimeout() | Установка таймаута для .parseInt() и .parseFloat() |
| .flush()      | Очистка буфера порта                               |
| .end()        | Закрытие порта                                     |
|---------------+----------------------------------------------------|
* Условия
** Операторы сравнения
Операторы сравнения используются для сравнения чего-либо:

|----------+--------------------------|
| Оператор | Описание                 |
|----------+--------------------------|
| x == y   | 'x' равен 'y'            |
| x != y   | 'x' *не* равен 'y'         |
| x > y    | 'x' больше 'y'           |
| x < y    | 'x' меньше 'y'           |
| x >= y   | 'x' больше или равен 'y' |
| x <= y   | 'x' меньше или равен 'y' |
|----------+--------------------------|

** Условный оператор 'if'

|----------+------------------------------------------------------------------|
| Оператор | Описание                                                         |
|----------+------------------------------------------------------------------|
| if(){}   | Если условие в '()' является истинным, то выполняется код в '{}' |
| else {}  | Если условие в '()' является ложным, то выполняется код в '{}'   |
|----------+------------------------------------------------------------------|

Пример:

#+begin_src c
boolean condition = true; // Переменная
Serial.begin(9600); // Открываем порт для вывода текста

if (condition) { // Если 'condition' является 'true'...
  Serial.println("Правда"); // ...то вывести в порт слово "True"...
} else { // ...если же нет...
  Serial.println("Ложь"); // ...то вывести в порт слово "False"
}
#+end_src

Так же можно использовать =else if() {}= в связке с =if=:

#+begin_src c
Serial.begin(9600); // Открываем порт для вывода

int a = 5; // Переменная 'a' равна 5

if (a == 3) { // Если 'a' равна 3...
  Serial.println("'a' равно 3");  // ..то выводим текст...
} else if (a > 10) { // ...если 'а' не равна трем, но больше 10...
  Serial.println("'a' больше 10"); // ...то выводим другой текст...
} else if (a == 2) { // ...если 'a' не равна 3, не больше 10, но равна 2...
  Serial.println("'a' равна 2"); // ...то выводим другой текст...
} else { // ...если 'a' не равна 3, не больше 10 и не равна 2...
  Serial.println(a); // ...то выводим значение переменной 'a'
}
#+end_src

** Логические операторы
|----------+------------------|
| Оператор | Описание         |
|----------+------------------|
| !        | Логическое 'НЕТ' |
| &&       | Логическое 'ИЛИ' |
|----------+------------------|

Пример с =!=:

#+begin_src c
x = !y; // Значение, противоположное 'y' записать в 'x'
#+end_src

Пример с =&&=:

#+begin_src c
Serial.begin(9600); // Открываем порт

int x = 12; // Присваеваем 'x' значение 12...
int y = 3; // ...а 'y' 3

if (x == 12 && y == 3) { // Если 'x' равен 12 а 'y' равен 3...
  Serial.println("'x' равен 12 а 'y' равен 3"); // ...то вывести текст
}
#+end_src

Так-же есть оператор =||= (логическое 'ИЛИ'):

#+begin_src c
if (x > 10 || y > 10) { // Если или 'x' или 'y' больше 10
  Serial.println("или 'x' или 'y' больше 10"); // ...то вывести текст
}
#+end_src

** Оператор 'switch'
Оператор =if= можно использовать когда условий не очень много, если условий 4 и больше, то лучше отдать предпочтение =switch=.

#+begin_src c
Serial.begin(9600);

int move = 3;

switch (move) { // Прогоняем ее через switch...
  case 1: // ...если ее значение равно 1...
    //...сделать что-то...
    break;
  case 2: // ... если же равно 2...
    // ... и так далее...
    break;
  // ...
}
#+end_src

* Время

|----------------------+-----------------------------------------------------------------|
| Функция              | Описание                                                        |
|----------------------+-----------------------------------------------------------------|
| delay(x)             | Задержка в *миллисекундах* 'x'                                    |
| delayMicroseconds(x) | Задержка в *микросекундах* 'x'                                    |
| millis()             | Возвращение времени в *миллисекундах* с момента запуска программы |
| micros()             | Возвращение времени в *микросекундах* с момента запуска программы |
|----------------------+-----------------------------------------------------------------|

Использование ~delay()~ в качестве задержки *не рекомендуется* в связи с тем, что она вешает весь микроконтроллер!
AlexGyver предлагает следующий код для решения этой проблемы:

#+begin_src c
unsigned long last_time; // глобальная переменная!!!

void loop() {
  if (millis() - last_time >= 5000) { // если прошло больше 5000 мс (5 секунд)
    // код, который выполняется каждые 5 секунд
    last_time = millis(); // сброс таймера
  }
}
#+end_src

* Порты (пины)
Существует два типа портов:
+ Аналоговые (с аналого-цифровым преобразователем)
+ Цифровые (без аналого-цифрового преобразователя)
Оба могут работать как *вход* ~INPUT~ и *выход* ~OUTPUT~. Чтобы узнать, какие пины на плате цифровые, а какие -  аналоговые, смотрите распиновку платы.

|--------------------+---------------------------------------------------------------------------|
| Метод              | Описание                                                                  |
|--------------------+---------------------------------------------------------------------------|
| pinMode(x, y)      | Настройка порт 'x' на режим работы 'y' (INPUT / OUTPUT / INPUT_PULLUP)    |
| digitalWrite(x, y) | Подача на порт 'x' *цифрового* сигнала 'y' (HIGH / LOW)                     |
| digitalRead(x)     | Чтение с порта 'x' *цифрового* сигнала                                      |
| analogWrite(x, y)  | Подача на порт 'x' *аналогового* сигнала 'y' (только для аналоговых портов) |
| analogRead(x)      | Чтение с порта 'x' *аналогового* сигнала (только для аналоговых портов)     |
|--------------------+---------------------------------------------------------------------------|

#+begin_src c
pinMode(13, OUTPUT); // Настраиваем порт 13 (с лампочкой) на вывод...
digitalWrite(13, HIGH); // ...подаем сигнал (лампочка включается)
#+end_src

На порте 13 есть лампочка, можно заставить ее мигать:

#+begin_src c
void setup() {
  pinMode(13, OUTPUT); // Открываем порт 13 на вывод
}

void loop() {
  digitalWrite(13, HIGH); // Подаем сигнал 5 Вольт (включаем) на 13 пин
  delay(1000); // Задержка в 1000 мс (1 секунда)
  digitalWrite(13, LOW); // Подаем сигнал 0 Вольт (выключаем) на 13 пин
  delay(1000); // Задержка
}
#+end_src

* Циклы
** 'while'
~while~ будет выполнять код в ~{}~ пока верно условие в ~()~
#+begin_src c
while (condition) { // Пока верно условие 'condition'...
  // ...выполнять этот код
}
#+end_src

Бесконечный цикл:
#+begin_src c
while (true) {
  // Какой-нибудь код
}
#+end_src

#+begin_src c
while (var >= 10) { // Пока переменная 'var' больше или равна 10...
  Serial.println("Привет, Мир!"); // ...Выводить в порт текст
}
#+end_src

** 'for'
В отличии от ~while~, ~for~ может в качестве аргумента принимать помимо условия переменную-счетчик и инкемент (увеличение переменной):

#+begin_src c
for (int c = 0; i <= 255; i++) { // Переменная-счетчик 'c', условие 'i <= 255', изменение переменной 'i++' (инкремент, или +1)
  Serial.println(i);
}
#+end_src

** 'break' и 'continue'

|----------+---------------------------|
| Оператор | Описание                  |
|----------+---------------------------|
| break    | Досрочно выйти из цикла   |
| continue | Пропустить итерацию цикла |
|----------+---------------------------|

#+begin_src c
for (int x = 0; x < 13; x++) {
  // ...
  if (x = 5) { // Если 'x' равен 5...
    x = 0; // ...то вернуть переменную-счетчик в начало...
    break; // ...и выйти из цикла...
  }
  // ...
}
#+end_src

* Функции
Функция - это код, который выполняется только тогда, когда его вызывают. К функции можно обратиться из разных мест программы. Так например, в Arduino ~setup~ и ~loop~ являются функциями, первая вызывается один раз при старте, вторая постоянно. Функция может возвращать или не возвращать результат. Вот простой пример функции:

#+begin_src c
void Function() {
  Serial.println("Вы вызвали функцию `Function!`");
}
#+end_src

Мы создали функцию с именем ~Function~, которая выводит сообщение в COM порт. Важно помнить две вещи: если мы имеем дело с локальными переменными из других функций, то они работать в другой функции не будут, их нужно передать в виде аргумента в ~()~ сделать глобальными:

#+begin_src c
void setup() {
  int a = 10;
}

void Function() {
  Serial.println(a); // Работать не будет!
}
#+end_src

Надо так:

#+begin_src c
void setup() {
  Serial.begin(9600);
  int a = 10;
  Function(a);
}

void Function(int variable) {
  Serial.println(variable);
}
#+end_src

Или на худой конец так (лучше не надо, но работать будет):

#+begin_src c
int a = 10;

void setup() {
  Serial.begin(9600);
  Function();
}

void Function() {
  Serial.println(a);
}
#+end_src

И то, что если мы изменим значение переменной /внутри функции/, то переменная *вне функции* значения *не изменит*. Это очень важно при работе с числами, например, в калькуляторе. Для того, чтобы функция могла вернуть новое значение переменной, нужно чтобы функция была инициализирована с помощью типа данных вместо ~void~. ~void~ *не может возвращать значения*!

#+begin_src c
void setup() {
  int number1 = 12;
  int number2 = 9;

  calculateSomething(number1, number2); // Передаем функции значение переменных 'number1' и 'number2'
}

int calculateSomething(int num1, int num2) { // Принимаем значение переменных как 'num1' и 'num2'
  return num1 * num2 - num1 // Вернуть первое число умноженное на второе число минус первое число (12 * 9 - 12)
}
#+end_src
