#+title: Математика
#+author: unenSCRIBE

* Содержание :toc:
- [[#алгебра][Алгебра]]
  - [[#натуральные-числа][Натуральные числа]]
- [[#геометрия][Геометрия]]
  - [[#основные-геометрические-фигуры][Основные геометрические фигуры]]

* Алгебра
** Натуральные числа
*** Признаки делимости

|-------+---------------------------------------------------------------|
| На 2  | Число оканчивается на четную цифру или 0                      |
| На 3  | Сумма цифр делится на 3                                       |
| На 4  | Число образованное из двух последних цифр делится на 4        |
| На 5  | Число оканчивается на 5 или 0                                 |
| На 6  | Число делится на 2 и на 3                                     |
| На 9  | Сумма цифр делится на 9                                       |
| На 11 | Суммы цифр взятых через одну равны или разность делится на 11 |
| На 18 | Число делится на 2 и 9                                        |
| На 25 | Число оканчивается на 00, 25, 50 или 75                       |
|-------+---------------------------------------------------------------|

*** Делители числа
N число, на которое другое N число делится без остатка, называется делителем этого числа. *Число 1 является делителем любого числа*. Делители числа не превосходят само число.

*** Дробь
Одна или несколько равных частей единицы называются обыкновенной дробью. Обыкновенная дробь записывается с помощью двух натуральных чисел и черты: $\frac{m}{n}$

Здесь /m/ - числитель, а /n/ - знаменатель. Если числитель меньше знаменателя, то дробь называется /правильной/. Если числитель больше или равен знаменателю, то такая дробь называется /неправильной/.

**** Основное свойство дроби
Если и числитель и знаменатель умножить или разделить на одно и то же число, то значение дроби не изменится. Деление числителя и знаменателя _на одно и то же число_ называется /сокращением/ дроби.

$$
\frac{15}{20} = \frac{15:5}{20:5} = \frac{3}{4}
$$

**** Смешанные числа
Чтобы представить неправильную дробь в виде смешанного числа, нужно числитель разделить на знаменатель, неполное частное записать в целую часть, остаток - в числитель, а делитель - в знаменатель:

$$
\frac{36}{7} = 36 : 7 = 5 (oc. 1)
$$

$$
\frac{36}{7} = 5\frac{1}{7}
$$

Чтобы перевести смешанное число в неправильную дробь, нужно целую часть умножить на знаменатель и прибавить числитель, полученное число записать в числитель, а знаменатель оставить тем же:

$$
7\frac{5}{17} = \frac{7 \cdot 17 + 5}{17} = \frac{124}{17}
$$

**** Десятичные дроби
Обыкновенная дробь, знаменатель которой равен 10, 100, 1000 и т.д. называется десятичной дробью. Целую часть отделяют от дробной запятой: $\frac{3}{10} = 0.3$

***** Округление

|-------------+-----------+---------|
| До сотых    | 236, 7541 |     200 |
| До десятков | 236, 7541 |     240 |
| До единиц   | 236, 7541 |     237 |
| До десятых  | 236, 7541 |   236,8 |
| До сотых    | 236, 7541 |  236,75 |
| До тысячных | 236, 7541 | 236,754 |
|-------------+-----------+---------|

* Геометрия
** Основные геометрические фигуры
Основными геометрическими фигурами являются /точка/, /прямая/ и /плоскость/.

*** Прямая
Обозначается одной малой латинской буквой или двумя заглавными.

#+html: <p align="center"> <img src="./math/1.svg"> </p>
